### ISSUE TITLE
Problem parsing in older .par files

### ISSUE THREAD

**Issue by twojenski** [compomics/compomics-utilities#10] opened 2016-02-10 18:16 UTC
I found a problem when I'm trying to import/parse in older .par files into PeptideShaker.

The actual problem is not with deserializing old .par files which could be either JSON or Binary.   The problem occurs in IdentificationParametersEditionDialog on line 285 when calling:  proteinInferencePreferences.getShortDescription()
It seems that ProteinInferencePreferences is a new attribute, and is never properly initialized by the old .par files.  When updateGUI() is called it gets a null Pointer when processing: proteinInferencePreferences.getShortDescription().

Regards

Tek Wojenski

**Comment by hbarsnes** [comment] 2016-02-10 21:31
Hi Tek,

Thanks for telling us about this. Would it be possible for you to send us the old parameter file so that we can try to reproduce and hopefully fix the issue?

Best regards,
Harald

**Comment by twojenski** [comment] 2016-02-11 00:06
Hello Harald

Sure.  Here are 2 .par files that will not work.
Essentially the newly introduced attribute proteinInferencePreferences
(see below) never get initialized properly in code because they do not
exist in the old .par files.
This causes the NULL Pointer Exception.   Please note that this may only be
the first attribute that causes a problem, there could be others once this
one is fixed.

"proteinInferencePreferences": {
    "proteinSequenceDatabase": {
      "path": "C:\\Work\\2\\2\\ABC.fasta"
    }
  },

Regards

Tek Wojenski

**Comment by hbarsnes** [comment] 2016-02-11 10:05
Hi Tek,

It seems like you tried to include the parameter files as attachment to your e-mail? I'm afraid this is not supported by GitHub. You'll have to log on to the issue tracker and upload the two files there.

Best regards,
Harald

**Comment by twojenski** [comment] 2016-02-11 11:51
Here they are, rename PDF to ZIP and first.  I could not upload .ZIP???





[de novogui_json.PDF](https://github.com/compomics/compomics-utilities/files/126265/de.novogui_json.PDF)

**Comment by hbarsnes** [comment] 2016-02-11 16:43
Hi Tek,

Thanks for the test files. The problem was that your parameter file came from DeNovoGUI and DeNovoGUI, for obvious reasons, does not have a FASTA file as part of its parameters. Which made it a bit difficult for us to show the name of the database in the dialog. :)

This has now been corrected and you should be able to load your parameter files in the next releases of SearchGUI and PeptideShaker, hopefully out tomorrow.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-02-12 12:37
Hi Tek,

The issue should be fixed with the new releases of SearchGUI, PeptideShaker and DeNovoGUI. Please let us know if there are other old parameter files you cannot load, as there might be some other special cases like this that we have not yet detected.

Best regards,
Harald

**Closed by hbarsnes** 2016-02-12 12:37 UTC
Labels: bug
