### ISSUE TITLE
IdentificationParametersCLI command line error

### ISSUE THREAD

**Issue by im281** [compomics/compomics-utilities#8] opened 2015-12-25 16:47 UTC
Hello, I keep getting an error while trying to run the IdentificationParametersCLI to create a parameters file.The command line I typed are below and the error is below that. Any suggestions would be appreciated.

java -cp SearchGUI-2.2.2.jar  eu.isas.searchgui.cmd.IdentificationParametersCLI -db "C:\SearchGUI-2.2.2\testfiles\my.fasta" -xtandem_npeaks 23 -out "c:\search_parameters.par"
java.lang.NullPointerException
        at com.compomics.util.preferences.IdentificationParameters.saveIdentificationParameters(IdentificationParameters.java:421)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.call(AbstractIdentificationParametersCli.java:107)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:84)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

**Comment by hbarsnes** [comment] 2015-12-26 01:10
Hi.

There seems to be a bug in our code when creating a new parameter file via the command line. We'll come up with fix and release a new version as soon as possible.

In the meantime you can always create the parameter file via the graphical user interface and then use it in your command lines. (Editing them via the command line should also be possible, as the bug above only seems to affect the creation of new parameters files.)

Best regards,
Harald

**Comment by im281** [comment] 2015-12-26 01:49
Thanks! Can't wait for the fix!

**Comment by im281** [comment] 2015-12-26 16:30
Looks like that bug is not fixed in 2.3.0 even though it says it was fixed in the release notes...

**Comment by im281** [comment] 2015-12-26 16:37
It appears that a input.par file created by the GUI can also not be saved

SearchGUI-2.3.0>java -cp SearchGUI-2.3.0.jar eu.isas.searchgui.cmd.IdentificationParametersCLI -db "C:\folder\myo.fasta" -out "C:/Users//Documents/idparams.par"


java.lang.NullPointerException
        at com.compomics.util.preferences.IdentificationParameters.saveIdentificationParameters(IdentificationParameters.java:421)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.call(AbstractIdentificationParametersCli.java:116)
        at com.compomics.util.experiment.identification.parameters_cli.AbstractIdentificationParametersCli.initiate(AbstractIdentificationParametersCli.java:93)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:25)
        at eu.isas.searchgui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:36)

**Comment by hbarsnes** [comment] 2015-12-26 21:15
Not sure which line in the release notes you are referring to, but I can confirm that the bug has not yet been fixed. Especially given that version 2.3.0 was released _before_ I replied to your comments. :-)

As for the line above regarding that a parameter file created in the GUI cannot be saved, I'm not sure what you mean? As the example above does not use a GUI generated parameter file at all?

**Comment by hbarsnes** [comment] 2015-12-26 21:20
And in case it is unclear from the documentation, if you want to use se GUI generated parameter file on the command line you have use the -id_params option. And in that case the -out option is not needed unless you want to make changes to the parameter file and resave it.

**Comment by im281** [comment] 2015-12-27 17:29
Ok thanks Herald!

**Comment by im281** [comment] 2016-01-04 01:30
Hi Herald, is the problem fixed in 2.3.2? It doesn't appear to be fixed? Thanks!

Changes in SearchGUI 2.3.1 (December 28. 2015):

BUG FIX: Fixed a bug in the creation of an identification settings file via the GUI.
LIBRARY UPDATE: Updated utilities to version 4.3.4.

**Comment by hbarsnes** [comment] 2016-01-04 16:28
Hi.

No, it was not fixed in version 2.3.2 (that issue was a related one but only when the file was created via the graphical user interface), but the issue has now been corrected and the fix will be in the next release. I will let you know when it becomes available.

Best regards,
Harald

**Comment by hbarsnes** [comment] 2016-01-05 20:37
Hi.

With the release of SearchGUI v2.3.3 and PeptideShaker v1.3.3 this issue has now been fixed. If this is not the case on your side please let us know and we'll reopen the issue.

Sorry it took so long, but you detect the issue at the worst time, i.e. right before the holidays. ;)

Best regards,
Harald

**Closed by hbarsnes** 2016-01-05 20:37 UTC
Labels: bug

**Comment by im281** [comment] 2016-01-05 20:39
No worries! I will check it out this evening...
Your program looks very promising!!

**Comment by im281** [comment] 2016-01-06 01:03
Thanks! It is working!!!

**Comment by im281** [comment] 2016-01-06 18:40
Hi Herald,
Is there a way to run SearchGUI using C#? For example:

System.Diagnostics.Process clientProcess = new Process();
           clientProcess.StartInfo.FileName = "java.exe";
           clientProcess.StartInfo.Arguments = "-jar" + " " +
@"SearchGUI-2.3.3\SearchGUI-2.3.3.jar" + [parameters];
           clientProcess.Start();


When I run this the splash screen pops up but no processing. The
command line works though.

**Comment by hbarsnes** [comment] 2016-01-06 21:38
The last question is a duplicate of https://github.com/compomics/peptide-shaker/issues/108. I will therefore reply to the question there.

Please limit the same question to a single issue on the future (and preferably don't add new questions to old closed issues), as otherwise it becomes very time consuming for us to keep track of all the issues. :)

**Comment by im281** [comment] 2016-01-06 21:43
ok sorry about that, didn't know where to post the question
